/* Generated By:JJTree: Do not edit this line. xquery-src/org/w3c/xqparser\XPathTreeConstants.java */

package org.w3c.xqparser;

public interface XPathTreeConstants {
	public int JJTXPATH2 = 0;
	public int JJTQUERYLIST = 1;
	public int JJTMODULE = 2;
	public int JJTVERSIONDECL = 3;
	public int JJTSTRINGLITERAL = 4;
	public int JJTMAINMODULE = 5;
	public int JJTLIBRARYMODULE = 6;
	public int JJTMODULEDECL = 7;
	public int JJTPROLOG = 8;
	public int JJTSETTER = 9;
	public int JJTIMPORT = 10;
	public int JJTSEPARATOR = 11;
	public int JJTNAMESPACEDECL = 12;
	public int JJTBOUNDARYSPACEDECL = 13;
	public int JJTDEFAULTNAMESPACEDECL = 14;
	public int JJTOPTIONDECL = 15;
	public int JJTORDERINGMODEDECL = 16;
	public int JJTEMPTYORDERDECL = 17;
	public int JJTGREATEST = 18;
	public int JJTLEAST = 19;
	public int JJTCOPYNAMESPACESDECL = 20;
	public int JJTPRESERVEMODE = 21;
	public int JJTINHERITMODE = 22;
	public int JJTDEFAULTCOLLATIONDECL = 23;
	public int JJTBASEURIDECL = 24;
	public int JJTSCHEMAIMPORT = 25;
	public int JJTSCHEMAPREFIX = 26;
	public int JJTMODULEIMPORT = 27;
	public int JJTVARDECL = 28;
	public int JJTEXTERNAL = 29;
	public int JJTCONSTRUCTIONDECL = 30;
	public int JJTFUNCTIONDECL = 31;
	public int JJTPARAMLIST = 32;
	public int JJTPARAM = 33;
	public int JJTENCLOSEDEXPR = 34;
	public int JJTLBRACE = 35;
	public int JJTLBRACEEXPRENCLOSURE = 36;
	public int JJTRBRACE = 37;
	public int JJTQUERYBODY = 38;
	public int JJTEXPR = 39;
	public int JJTVOID = 40;
	public int JJTFLWOREXPR = 41;
	public int JJTFORCLAUSE = 42;
	public int JJTPOSITIONALVAR = 43;
	public int JJTLETCLAUSE = 44;
	public int JJTWHERECLAUSE = 45;
	public int JJTORDERBYCLAUSE = 46;
	public int JJTORDERSPECLIST = 47;
	public int JJTORDERSPEC = 48;
	public int JJTORDERMODIFIER = 49;
	public int JJTASCENDING = 50;
	public int JJTDESCENDING = 51;
	public int JJTQUANTIFIEDEXPR = 52;
	public int JJTTYPESWITCHEXPR = 53;
	public int JJTCASECLAUSE = 54;
	public int JJTIFEXPR = 55;
	public int JJTOREXPR = 56;
	public int JJTANDEXPR = 57;
	public int JJTCOMPARISONEXPR = 58;
	public int JJTRANGEEXPR = 59;
	public int JJTADDITIVEEXPR = 60;
	public int JJTMULTIPLICATIVEEXPR = 61;
	public int JJTUNIONEXPR = 62;
	public int JJTINTERSECTEXCEPTEXPR = 63;
	public int JJTINSTANCEOFEXPR = 64;
	public int JJTTREATEXPR = 65;
	public int JJTCASTABLEEXPR = 66;
	public int JJTCASTEXPR = 67;
	public int JJTUNARYEXPR = 68;
	public int JJTMINUS = 69;
	public int JJTPLUS = 70;
	public int JJTVALIDATEEXPR = 71;
	public int JJTVALIDATIONMODE = 72;
	public int JJTEXTENSIONEXPR = 73;
	public int JJTPRAGMA = 74;
	public int JJTPRAGMAOPEN = 75;
	public int JJTS = 76;
	public int JJTQNAMEFORPRAGMA = 77;
	public int JJTSFORPRAGMA = 78;
	public int JJTPRAGMACLOSE = 79;
	public int JJTPRAGMACONTENTS = 80;
	public int JJTEXTENSIONCONTENTCHAR = 81;
	public int JJTPATHEXPR = 82;
	public int JJTSLASH = 83;
	public int JJTSLASHSLASH = 84;
	public int JJTSTEPEXPR = 85;
	public int JJTFORWARDAXIS = 86;
	public int JJTABBREVFORWARDSTEP = 87;
	public int JJTREVERSEAXIS = 88;
	public int JJTABBREVREVERSESTEP = 89;
	public int JJTNODETEST = 90;
	public int JJTNAMETEST = 91;
	public int JJTWILDCARD = 92;
	public int JJTNCNAMECOLONSTAR = 93;
	public int JJTSTARCOLONNCNAME = 94;
	public int JJTPREDICATELIST = 95;
	public int JJTPREDICATE = 96;
	public int JJTINTEGERLITERAL = 97;
	public int JJTDECIMALLITERAL = 98;
	public int JJTDOUBLELITERAL = 99;
	public int JJTVARNAME = 100;
	public int JJTPARENTHESIZEDEXPR = 101;
	public int JJTCONTEXTITEMEXPR = 102;
	public int JJTORDEREDEXPR = 103;
	public int JJTUNORDEREDEXPR = 104;
	public int JJTFUNCTIONCALL = 105;
	public int JJTCONSTRUCTOR = 106;
	public int JJTDIRECTCONSTRUCTOR = 107;
	public int JJTDIRELEMCONSTRUCTOR = 108;
	public int JJTLESSTHANOPORTAGO = 109;
	public int JJTSTARTTAGOPEN = 110;
	public int JJTTAGQNAME = 111;
	public int JJTEMPTYTAGCLOSE = 112;
	public int JJTSTARTTAGCLOSE = 113;
	public int JJTENDTAGQNAME = 114;
	public int JJTDIRATTRIBUTELIST = 115;
	public int JJTVALUEINDICATOR = 116;
	public int JJTDIRATTRIBUTEVALUE = 117;
	public int JJTOPENQUOT = 118;
	public int JJTESCAPEQUOT = 119;
	public int JJTCLOSEQUOT = 120;
	public int JJTOPENAPOS = 121;
	public int JJTESCAPEAPOS = 122;
	public int JJTCLOSEAPOS = 123;
	public int JJTQUOTATTRVALUECONTENT = 124;
	public int JJTQUOTATTRCONTENTCHAR = 125;
	public int JJTAPOSATTRVALUECONTENT = 126;
	public int JJTAPOSATTRCONTENTCHAR = 127;
	public int JJTDIRELEMCONTENT = 128;
	public int JJTELEMENTCONTENTCHAR = 129;
	public int JJTCOMMONCONTENT = 130;
	public int JJTPREDEFINEDENTITYREF = 131;
	public int JJTCHARREF = 132;
	public int JJTLCURLYBRACEESCAPE = 133;
	public int JJTRCURLYBRACEESCAPE = 134;
	public int JJTDIRCOMMENTCONSTRUCTOR = 135;
	public int JJTXMLCOMMENTSTARTFORELEMENTCONTENT = 136;
	public int JJTXMLCOMMENTSTART = 137;
	public int JJTXMLCOMMENTEND = 138;
	public int JJTDIRCOMMENTCONTENTS = 139;
	public int JJTCOMMENTCONTENTCHAR = 140;
	public int JJTCOMMENTCONTENTCHARDASH = 141;
	public int JJTDIRPICONSTRUCTOR = 142;
	public int JJTPROCESSINGINSTRUCTIONSTARTFORELEMENTCONTENT = 143;
	public int JJTPROCESSINGINSTRUCTIONSTART = 144;
	public int JJTPITARGET = 145;
	public int JJTSFORPI = 146;
	public int JJTPROCESSINGINSTRUCTIONEND = 147;
	public int JJTDIRPICONTENTS = 148;
	public int JJTPICONTENTCHAR = 149;
	public int JJTCDATASECTION = 150;
	public int JJTCDATASECTIONSTARTFORELEMENTCONTENT = 151;
	public int JJTCDATASECTIONSTART = 152;
	public int JJTCDATASECTIONEND = 153;
	public int JJTCDATASECTIONCONTENTS = 154;
	public int JJTCDATASECTIONCHAR = 155;
	public int JJTCOMPUTEDCONSTRUCTOR = 156;
	public int JJTCOMPDOCCONSTRUCTOR = 157;
	public int JJTCOMPELEMCONSTRUCTOR = 158;
	public int JJTCONTENTEXPR = 159;
	public int JJTCOMPATTRCONSTRUCTOR = 160;
	public int JJTCOMPTEXTCONSTRUCTOR = 161;
	public int JJTCOMPCOMMENTCONSTRUCTOR = 162;
	public int JJTCOMPPICONSTRUCTOR = 163;
	public int JJTSINGLETYPE = 164;
	public int JJTTYPEDECLARATION = 165;
	public int JJTSEQUENCETYPE = 166;
	public int JJTOCCURRENCEINDICATOR = 167;
	public int JJTITEMTYPE = 168;
	public int JJTATOMICTYPE = 169;
	public int JJTANYKINDTEST = 170;
	public int JJTDOCUMENTTEST = 171;
	public int JJTTEXTTEST = 172;
	public int JJTCOMMENTTEST = 173;
	public int JJTPITEST = 174;
	public int JJTATTRIBUTETEST = 175;
	public int JJTATTRIBNAMEORWILDCARD = 176;
	public int JJTSCHEMAATTRIBUTETEST = 177;
	public int JJTATTRIBUTEDECLARATION = 178;
	public int JJTELEMENTTEST = 179;
	public int JJTELEMENTNAMEORWILDCARD = 180;
	public int JJTSCHEMAELEMENTTEST = 181;
	public int JJTELEMENTDECLARATION = 182;
	public int JJTATTRIBUTENAME = 183;
	public int JJTELEMENTNAME = 184;
	public int JJTTYPENAME = 185;
	public int JJTURILITERAL = 186;
	public int JJTNCNAME = 187;
	public int JJTQNAME = 188;
	public int JJTFUNCTIONQNAME = 189;

	public String[] jjtNodeName = { "XPath2", "QueryList", "Module", "VersionDecl", "StringLiteral", "MainModule",
			"LibraryModule", "ModuleDecl", "Prolog", "Setter", "Import", "Separator", "NamespaceDecl",
			"BoundarySpaceDecl", "DefaultNamespaceDecl", "OptionDecl", "OrderingModeDecl", "EmptyOrderDecl", "Greatest",
			"Least", "CopyNamespacesDecl", "PreserveMode", "InheritMode", "DefaultCollationDecl", "BaseURIDecl",
			"SchemaImport", "SchemaPrefix", "ModuleImport", "VarDecl", "External", "ConstructionDecl", "FunctionDecl",
			"ParamList", "Param", "EnclosedExpr", "Lbrace", "LbraceExprEnclosure", "Rbrace", "QueryBody", "Expr",
			"void", "FLWORExpr", "ForClause", "PositionalVar", "LetClause", "WhereClause", "OrderByClause",
			"OrderSpecList", "OrderSpec", "OrderModifier", "Ascending", "Descending", "QuantifiedExpr",
			"TypeswitchExpr", "CaseClause", "IfExpr", "OrExpr", "AndExpr", "ComparisonExpr", "RangeExpr",
			"AdditiveExpr", "MultiplicativeExpr", "UnionExpr", "IntersectExceptExpr", "InstanceofExpr", "TreatExpr",
			"CastableExpr", "CastExpr", "UnaryExpr", "Minus", "Plus", "ValidateExpr", "ValidationMode", "ExtensionExpr",
			"Pragma", "PragmaOpen", "S", "QNameForPragma", "SForPragma", "PragmaClose", "PragmaContents",
			"ExtensionContentChar", "PathExpr", "Slash", "SlashSlash", "StepExpr", "ForwardAxis", "AbbrevForwardStep",
			"ReverseAxis", "AbbrevReverseStep", "NodeTest", "NameTest", "Wildcard", "NCNameColonStar",
			"StarColonNCName", "PredicateList", "Predicate", "IntegerLiteral", "DecimalLiteral", "DoubleLiteral",
			"VarName", "ParenthesizedExpr", "ContextItemExpr", "OrderedExpr", "UnorderedExpr", "FunctionCall",
			"Constructor", "DirectConstructor", "DirElemConstructor", "LessThanOpOrTagO", "StartTagOpen", "TagQName",
			"EmptyTagClose", "StartTagClose", "EndTagQName", "DirAttributeList", "ValueIndicator", "DirAttributeValue",
			"OpenQuot", "EscapeQuot", "CloseQuot", "OpenApos", "EscapeApos", "CloseApos", "QuotAttrValueContent",
			"QuotAttrContentChar", "AposAttrValueContent", "AposAttrContentChar", "DirElemContent",
			"ElementContentChar", "CommonContent", "PredefinedEntityRef", "CharRef", "LCurlyBraceEscape",
			"RCurlyBraceEscape", "DirCommentConstructor", "XmlCommentStartForElementContent", "XmlCommentStart",
			"XmlCommentEnd", "DirCommentContents", "CommentContentChar", "CommentContentCharDash", "DirPIConstructor",
			"ProcessingInstructionStartForElementContent", "ProcessingInstructionStart", "PITarget", "SForPI",
			"ProcessingInstructionEnd", "DirPIContents", "PIContentChar", "CDataSection",
			"CdataSectionStartForElementContent", "CdataSectionStart", "CdataSectionEnd", "CDataSectionContents",
			"CDataSectionChar", "ComputedConstructor", "CompDocConstructor", "CompElemConstructor", "ContentExpr",
			"CompAttrConstructor", "CompTextConstructor", "CompCommentConstructor", "CompPIConstructor", "SingleType",
			"TypeDeclaration", "SequenceType", "OccurrenceIndicator", "ItemType", "AtomicType", "AnyKindTest",
			"DocumentTest", "TextTest", "CommentTest", "PITest", "AttributeTest", "AttribNameOrWildcard",
			"SchemaAttributeTest", "AttributeDeclaration", "ElementTest", "ElementNameOrWildcard", "SchemaElementTest",
			"ElementDeclaration", "AttributeName", "ElementName", "TypeName", "URILiteral", "NCName", "QName",
			"FunctionQName", };
}
