/* Generated By:JJTree: Do not edit this line. xquery-src/org/w3c/xqparser\XPathVisitor.java */

package org.w3c.xqparser;

public interface XPathVisitor {
	public Object visit(SimpleNode node, Object data);
}
